### ISSUE TITLE
Two day Shipping - Editing

### ISSUE THREAD

**Issue by cerdamejiaj** [ZachAndrews98/ZachAndrews98.github.io#3]
First Paragraph

-  Put a comma after However

- I think you should say based on instead of based around.

Second Paragraph 

- put a comma after Prime

- Change "in order to" to just to. Ex "I was ordering I tried every way I could to save a couple of dollars" and add of after couple.

Third Paragraph

- put a comma after mogul .

- you might want to rewrite this sentence, "provide people with access to a large quantity of quality items." Ex "other sites that provide people with access to many quality items"

- T-shirts
- knick-knacks

**Comment by ZachAndrews98** [comment]
I've been reading my article and I don't think that the third paragraph fits with the rest of the article. What do you think?

**Comment by cerdamejiaj** [comment]
I think your third paragraph fits with your article because you are still talking about other services that have two-day shipping and how they have benefited you.

**Comment by ZachAndrews98** [comment]
Alright, I'm going to push the changes I have made, take a look.
