### ISSUE TITLE
Prying Eyes Suggestions

### ISSUE THREAD

**Issue by nadeld** [ZachAndrews98/ZachAndrews98.github.io#4]
A suggestion that I have for your paper is to talk about how we can address cyber-stalking and ways to prevent it from happening.

**Comment by ZachAndrews98** [comment]
Yeah I had planned on finishing my article with talking about how this could possibly be resolved by google

**Comment by nadeld** [comment]
Nice! I see that you have a completed article; however, I think you should provide the attributions for your article image. I like how you have a direct link to your sources.

**Comment by ZachAndrews98** [comment]
Thanks, I had it in there earlier but I guess it got removed by accident.

**Comment by nadeld** [comment]
1st paragraph:
1st sentence- often times should be one word. 
2nd sentence- They're should be their.
3rd sentence-  fluff--->or whatever the term is for that particular site

2nd paragraph: 
1st sentence- what ability? you simply state this ability. I would transition differently.
4th sentence-The Google search engine can allow people to find out the best route to get from point A to point B, can allow people to find local services that are needed like plumbers, locksmiths, etc. (change this sentence and instead of saying can allow people, say allows people.

3rd paragraph:
1st sentence-  -the disconnect between you and the person that may or may not be stalking you who may have never been in the same area as you, cyberstalkers may be impossible or at the very least hard to get rid of. (confusing sentence)

4th paragraph:
1st sentence-There are countless examples of this occurring, most of which do not have a happy ending.  (create a better transition)
