### ISSUE TITLE
Piracy Portrait

### ISSUE THREAD

**Issue by nadeld** [ZachAndrews98/ZachAndrews98.github.io#7]
I see that you have begun your into paragraph; however, I do not see any questions added to your paper. One thing I would fix is that the third sentence starts off with "From".

**Comment by ZachAndrews98** [comment]
Thanks, David
I've been working on it a lot on my home computer which I can't push from which is why there is not a lot of content. And I'll make sure to fix my wording in my introduction.

**Comment by nadeld** [comment]
Thank you Zach!
