### ISSUE TITLE
Plagarism 

### ISSUE THREAD

**Issue by zbzoll** [ZachAndrews98/ZachAndrews98.github.io#8]
near the end of the of your first paragraph, your writing style changed have normal writing to Italics which I don't know if you did that on purpose

**Comment by ZachAndrews98** [comment]
Thanks for your input, however, that segment is formatted that way because I am not sure if I will keep that in my article.

**Comment by ZachAndrews98** [comment]
Besides that formatting do you have any edits for me to make?

**Comment by zbzoll** [comment]
oh, that make sense.
Including the website at the bottom where you got your quote
In your second paragraph after this see below you should add a comma 

Issue: Plagiarism has become increasingly easy for students to do**,** thanks

**Comment by ZachAndrews98** [comment]
I've finished my article, please take a look and give any suggestions.

**Comment by zbzoll** [comment]
it looked pretty good to me

**Comment by ZachAndrews98** [comment]
Alright, thanks!

**Comment by zbzoll** [comment]
it looked pretty good to me
